name: continuous-integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-book:
    runs-on: ubuntu-latest
    container:
      image: michaelfbryan/mdbook-docker-image
    steps:
    - uses: actions/checkout@v2.4.0
    - run: mdbook build
    - uses: actions/upload-artifact@v2
      with:
        name: book
        path: ./book

  upload-book:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: build-book
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: book
          path: ./book
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
